"""
Broker abstraction layer.

Defines the contract that ALL broker implementations must satisfy:
  - PaperBroker - fills at live Yahoo Finance price

The Strategy pattern here means OrderManager never changes when we swap brokers.
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum

# Enums


class OrderStatus(StrEnum):
    """Complete lifecycle of an order.

    State transitions:
        PENDING -> FILLED      : broker confirmed execution
        PENDING -> REJECTED    : broker refused (price moved, market closed, etc.)
        PENDING -> CANCELLED   : user cancelled before fill
        FILLED  -> CLOSED      : take-profit hit or manual exit
        FILLED  -> STOPPED_OUT : stop-loss hit
    """

    PENDING = "PENDING"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    CLOSED = "CLOSED"
    STOPPED_OUT = "STOPPED_OUT"


class OrderSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


# Data contracts


@dataclass
class RiskDecision:
    """Clean handoff between Sprint 3 (risk) and Sprint 4 (execution).

    The OrderManager receives a RiskDecision and builds an Order from it.
    This separates concerns: risk engine doesn't know about order mechanics,
    and the broker doesn't know about risk rules.

    Fields
    ------
    symbol          : e.g. "RELIANCE.NS"
    side            : BUY or SELL
    shares          : from PositionSizer.size()
    entry_price     : latest scanned price (informational; broker re-fetches live price)
    stop_loss       : absolute price level for stop-loss
    take_profit     : absolute price level for take-profit
    confidence      : aggregated signal confidence (0.0 – 1.0)
    strategy        : which strategy triggered this (e.g. "multi_agent")
    agent_reasoning : human-readable explanation from the aggregator
    capital_at_risk : total rupees at risk on this trade
    """

    symbol: str
    side: OrderSide
    shares: int
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float
    strategy: str
    agent_reasoning: str
    capital_at_risk: float


@dataclass
class Order:
    """Represents a single order through its full lifecycle.

    The order_id is generated BEFORE submission so we can check idempotency
    in the DB before ever calling the broker.

    Fields set at creation
    ----------------------
    order_id        : UUID generated by caller, used for idempotency
    symbol, side, shares, strategy, agent_reasoning, confidence
    requested_price : the price at scan time (may differ from fill_price)
    stop_loss, take_profit, capital_at_risk

    Fields set on fill
    ------------------
    fill_price      : actual execution price fetched live at fill time
    fill_timestamp  : when the broker filled it
    slippage        : fill_price - requested_price (negative = better fill)

    Fields set on close
    -------------------
    exit_price, exit_timestamp, exit_reason
    pnl, pnl_pct, r_multiple
    """

    # Identity
    order_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str = ""
    side: OrderSide = OrderSide.BUY

    # Sizing
    shares: int = 0
    requested_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    capital_at_risk: float = 0.0

    # Context
    strategy: str = ""
    agent_reasoning: str = ""
    confidence: float = 0.0

    # Lifecycle
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime = field(default_factory=datetime.utcnow)

    # Fill details (populated by broker)
    fill_price: float | None = None
    fill_timestamp: datetime | None = None
    slippage: float | None = None  # fill_price - requested_price

    # Exit details (populated when position closes)
    exit_price: float | None = None
    exit_timestamp: datetime | None = None
    exit_reason: str | None = None  # "take_profit", "stop_loss", "manual"

    # Performance (calculated on close)
    pnl: float | None = None
    pnl_pct: float | None = None
    r_multiple: float | None = None  # pnl / capital_at_risk

    @classmethod
    def from_risk_decision(cls, decision: RiskDecision, order_id: str | None = None) -> Order:
        """Build an Order from a RiskDecision.

        The order_id can be pre-supplied (for idempotency replay) or generated fresh.
        """
        return cls(
            order_id=order_id or str(uuid.uuid4()),
            symbol=decision.symbol,
            side=decision.side,
            shares=decision.shares,
            requested_price=decision.entry_price,
            stop_loss=decision.stop_loss,
            take_profit=decision.take_profit,
            capital_at_risk=decision.capital_at_risk,
            strategy=decision.strategy,
            agent_reasoning=decision.agent_reasoning,
            confidence=decision.confidence,
        )

    @property
    def position_value(self) -> float:
        """Total position value at fill price (0 if not filled yet)."""
        if self.fill_price is None:
            return 0.0
        return self.shares * self.fill_price

    @property
    def is_open(self) -> bool:
        return self.status == OrderStatus.FILLED

    @property
    def is_terminal(self) -> bool:
        """True when no further state transitions are possible."""
        return self.status in (
            OrderStatus.CLOSED,
            OrderStatus.STOPPED_OUT,
            OrderStatus.REJECTED,
            OrderStatus.CANCELLED,
        )


# Abstract broker interface (Strategy pattern)


class BrokerInterface(ABC):
    """Contract all broker implementations must satisfy.

    Why abstract?
    PaperBroker and UpstoxBroker have very different internals —
    one fetches a Yahoo Finance price, the other calls a REST API —
    but OrderManager only cares about submit() and close_position().
    Swapping brokers requires zero changes to OrderManager.
    """

    @abstractmethod
    def submit(self, order: Order) -> Order:
        """Submit an order for execution.

        Implementations should:
        1. Fetch the current live price
        2. Simulate (paper) or send (live) the order
        3. Set fill_price, fill_timestamp, slippage on the order
        4. Set status to FILLED or REJECTED
        5. Return the mutated order

        The caller (OrderManager) is responsible for DB persistence.
        The broker should NOT write to the DB directly.
        """
        ...

    @abstractmethod
    def close_position(self, order: Order, reason: str) -> Order:
        """Close an open position.

        Implementations should:
        1. Fetch the current live price
        2. Set exit_price, exit_timestamp, exit_reason on the order
        3. Calculate pnl, pnl_pct, r_multiple
        4. Set status to CLOSED or STOPPED_OUT
        5. Return the mutated order
        """
        ...
